# Generated by Django 5.2.3 on 2025-07-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], max_length=10, unique=True)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('emergency_medical', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip_cancellation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('baggage_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adventure_sports', models.BooleanField(default=False)),
                ('rental_car_coverage', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
