# Generated by Django 5.2.3 on 2025-07-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('aadhar_number', models.CharField(max_length=12)),
                ('trip_name', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('policy_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
